creación de componente NavBar
MacarenaRodriguez1993/Emme-3D pull request #32
Opened 2022-12-06 22:33 UTC by MacarenaRodriguez1993

#17 
Se agrego react router -  redux
Se creo component navBar para ser reutilizado cuando sea necesario.
Tiene estilos css puro, al momento que se agregue la instalacion de tailwind reacomodo eso.

2022-12-06 22:46 UTC, Pau-Marin approved these changes

2022-12-07 00:45 UTC, Pau-Marin requested changes

2022-12-07 00:45 UTC, Pau-Marin commented on client/src/main.jsx
> +    </BrowserRouter>
Ahora que me fijo mejor, en el main.jsx se está quitando el store de Redux, creo que falta bajarse el estado actual de la rama dev antes del push

2022-12-07 00:45 UTC, Pau-Marin commented on client/src/App.jsx
> +
Habrá que ponerse de acuerdo entre todos los que toquen front para que los componentes se creen de la misma manera, si no tendremos muchos cambios de este tipo y pueden llevar a confusión cuando se modifiquen varios componentes

2022-12-07 02:46 UTC, MacarenaRodriguez1993 commented on client/src/App.jsx
> +
Perfecto. Me gusta mas así
const Nombre = ()=>{
}

2022-12-07 03:10 UTC, MacarenaRodriguez1993 commented
Ahí acomode las cosas que me comentabas @Pau-Marin, me colgue en crear una nueva rama por lo que aqui ya implemente el footer también. La próxima tarea va desde la nueva rama (eso espero  jaja )

2022-12-07 11:07 UTC, Pau-Marin approved these changes

2022-12-07 11:10 UTC, merged

2022-12-08 16:37 UTC, Pau-Marin commented
Closes #20